# NumPy

In [1]:
# Import NumPy 
import numpy as np

## Resource
https://numpy.org/doc/stable/user/absolute_beginners.html

## Multidimensional Homogeneous Arrays

In [2]:
# A 2D array of integers
a = np.array([[1, 2, 3],[4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
# Print the shape of the array
print(a.shape)

(2, 3)


In [4]:
# Print the type of the elements in the array
print(a.dtype)

int64


In [5]:
# print dimension of the array
print(a.ndim)

2


# Operations

In [6]:
## Two arrays.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Show.
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [7]:
# Adding constants.
A + 5

array([[6, 7],
       [8, 9]])

In [8]:
# Multiplying by a constant.
A * 2

array([[2, 4],
       [6, 8]])

In [9]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [10]:
# Matrix multiplication.
A @ B

array([[19, 22],
       [43, 50]])